GET http://localhost:3000/api/v1/items
content-type: application/json

###
GET http://localhost:3000/api/v1/items/:id
content-type: application/json

###
PATCH http://localhost:3000/api/v1/items/:id
content-type: application/json

{
  "price": 40.9
}

###
POST http://localhost:3000/api/v1/cart
content-type: application/json

{
  "items": [
    {
      "code": "MUG",
      "quantity": 2
    },
    {
      "code": "TSHIRT",
      "quantity": 4
    },
    {
      "code": "HOODIE",
      "quantity": 1
    }
  ]
}

###
POST http://localhost:3000/api/v1/cart
content-type: application/json

{
  "items": [
    {
      "code": "XYX",
      "quantity": 2
    }
  ]
}
